# Calculative Foundation


In [6]:
import pandas as pd 
import numpy as np

df=pd.read_csv('C:/Users/Lenovo/Desktop/Maths/pr 4/student_scores_200.csv')
df

,Student_ID,First_Name,Last_Name,Full_Name,Math,Science,English,History,Total_Score,Average_Score,Grade,Status
0,STU_001,Jennifer,Garcia,Jennifer Garcia,74,65,81,80,300,75.00,C,Pass
1,STU_002,Aaron,Brown,Aaron Brown,72,72,84,80,308,77.00,C,Pass
2,STU_003,David,Carter,David Carter,80,90,70,73,313,78.25,C,Pass
3,STU_004,Justin,Cook,Justin Cook,89,59,84,86,318,79.50,C,Pass
4,STU_005,Justin,Anderson,Justin Anderson,79,93,86,83,341,85.25,B,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
195,STU_196,Zachary,Hernandez,Zachary Hernandez,90,73,63,80,306,76.50,C,Pass
196,STU_197,Ashley,Reed,Ashley Reed,67,51,67,59,244,61.00,D,Pass
197,STU_198,Tyler,Lopez,Tyler Lopez,66,76,71,87,300,75.00,C,Pass
198,STU_199,Ethan,Stewart,Ethan Stewart,86,81,72,65,304,76.00,C,Pass


1.	Represent each student’s subject scores as a vector.

In [4]:
subjects = ["Math","Science","English","History"]
v=[]
for i in range(200):
  student_vector = df.loc[i,subjects].astype(float).tolist()
  v.append(student_vector)

choice=int(input('enter student index for its vector: '))
print(v[choice])

[89.0, 59.0, 84.0, 86.0]


2.	Compute:
○	Norm-1 and Norm-2 of vectors.

In [ ]:
choice=int(input('enter index:'))
l1=np.linalg.norm(v[choice],ord=1)
l2=np.linalg.norm(v[choice],ord=2)
print('student vector:',v[choice])
print('norm1:',l1)
print('norm2:',l2)

student vector: [89.0, 59.0, 84.0, 86.0]
norm 1: 318.0
norm 2: 160.7917908352289


○	Dot product and angle between two students’ score vectors.

In [ ]:
s1=int(input(' first student index: '))
s2=int(input(' second student index: '))
dot=np.dot(v[s1],v[s2])
mag_1=np.linalg.norm(v[s1])
mag_2=np.linalg.norm(v[s2])
angle=dot/(mag_1*mag_2)
print('dot product:',dot)
print(np.degrees(np.arccos(angle)))
print(dot)

dot product: 26880.0
11.840282666070335
26880.0


○	Cross product (for 3D selected subjects).

In [11]:
subjects_3d=['Math','Science','English']
choice1=int(input(' first student index: '))
choice2=int(input(' second student index: '))
vec1=df.loc[choice1,subjects_3d].astype(float).values
vec2=df.loc[choice2,subjects_3d].astype(float).values
cross_product=np.cross(vec1,vec2)
print(cross_product)

[0. 0. 0.]


3.	Find the projection of one vector onto another.

In [13]:
c1=int(input('first student index: '))
c2=int(input('second student index: '))

dot=np.dot(v[c1],v[c2])
mag_b=np.linalg.norm(v[c2])
vector_dot=dot/(mag_b**2)
proj=np.dot(vector_dot,v[c2])
mag=np.linalg.norm(proj)
print('the projection of vector1 on to vector2:',proj)
print('the magnitude of the projection:',mag)

the projection of vector1 on to vector2: [74. 65. 81. 80.]
the magnitude of the projection: 150.53903148353254


4.	Form a matrix of students × subjects. Perform:

○	Matrix addition and multiplication.

In [19]:
matrix = np.array(v, dtype=np.float64)
print(matrix[:4])
mat_add=matrix+matrix
print('Matrix addition',mat_add[:4])
mat_mul=matrix @ matrix.T
print('Matrix multiplication',mat_mul[0])


[[74. 65. 81. 80.]
 [72. 72. 84. 80.]
 [80. 90. 70. 73.]
 [89. 59. 84. 86.]]
Matrix addition [[148. 130. 162. 160.]
 [144. 144. 168. 160.]
 [160. 180. 140. 146.]
 [178. 118. 168. 172.]]
Matrix multiplication [22662. 23212. 23280. 24105. 25497. 23900. 21887. 20761. 24120. 24242.
 22204. 18675. 22034. 21766. 24771. 24555. 23647. 19251. 20323. 24303.
 23629. 26749. 25594. 25218. 24124. 20667. 22876. 23372. 22487. 23364.
 19241. 22179. 20503. 22253. 22469. 23782. 22408. 20969. 23104. 25291.
 21020. 23896. 23273. 23333. 22063. 24472. 22440. 22690. 22568. 20512.
 19664. 19856. 21284. 22314. 25346. 22367. 21420. 21424. 23012. 21334.
 24769. 23626. 23569. 20577. 20585. 22460. 22055. 21725. 21856. 24599.
 21010. 22334. 20387. 21851. 23714. 22152. 22764. 22682. 24335. 22635.
 21642. 24042. 22956. 22614. 22126. 21685. 21064. 21697. 22898. 22753.
 25396. 21674. 22596. 22095. 18366. 23489. 24194. 22070. 19574. 23375.
 24424. 21176. 22979. 21884. 20825. 22186. 25597. 23367. 23142. 22426.
 23933. 240

○	Transpose and Inverse (if possible).

In [26]:
transpose=matrix.T
print(transpose[0][:20])

# inverse
small_mat=matrix[:4]
determinant=np.linalg.det(small_mat)
# determiant is non-zero so inverse of matrix is possible
inverse=np.linalg.inv(small_mat)
print(inverse)


[74. 72. 80. 89. 79. 69. 63. 76. 75. 68. 64. 64. 85. 67. 75. 83. 89. 43.
 71. 72.]
[[-0.27726609  0.13781519  0.01117318  0.12023756]
 [ 0.01303538 -0.00139665  0.02234637 -0.02979516]
 [-0.54859329  0.42846897 -0.04469274  0.14968041]
 [ 0.81383059 -0.56016911  0.01675978 -0.23856258]]


○	Determinant.

In [27]:
small_matrix=matrix[:4] # convertin 200,5 into 5,5
determinant=np.linalg.det(small_matrix)
print(determinant)

79475.99999999991


7.	Compute the eigenvalues and eigenvectors of the covariance matrix.

In [28]:
cov_mat=np.cov(matrix,rowvar=False)
new=np.round(cov_mat,2)
eigenvalues,eigenvectors=np.linalg.eig(new)
print(eigenvalues)
print(eigenvectors)

[179.83349561 163.83166404 133.87542478 106.80941557]
[[ 0.70436488 -0.70605609 -0.07311708  0.00296618]
 [-0.61165767 -0.65087206  0.4010743   0.20342039]
 [-0.04598417  0.00906802 -0.49535941  0.86742278]
 [ 0.35725406  0.27886937  0.76708041  0.45408046]]
